import Foundation

/// Dispatches log entries to pattern detectors and metrics snapshots to
/// metrics detectors, collecting alerts from both.
///
/// `DetectorPipeline` is an actor that owns all detectors and coordinates
/// two data flows:
/// - LogEntry → accepts() filter → process() → [Alert]
/// - SystemMetrics → process() → [Alert]
///
/// Thread-safe by design (Swift actor). Periodic `tick()` calls allow
/// detectors to emit time-based alerts and clean up stale state.
public actor DetectorPipeline {

    private var detectors: [PatternDetector]
    private var metricsDetectors: [MetricsDetector]

    /// Entries with timestamps before this are silently dropped.
    /// Prevents stale buffered log entries from triggering false alerts.
    private let startTime: Date

    /// Creates a pipeline with all detectors from `PatternCatalog` and `MetricsCatalog`.
    public init() {
        self.detectors = PatternCatalog.makeAll()
        self.metricsDetectors = MetricsCatalog.makeAll()
        self.startTime = Date()
    }

    /// Creates a pipeline with the given pattern detectors (for testing).
    /// No metrics detectors are added.
    public init(detectors: [PatternDetector]) {
        self.detectors = detectors
        self.metricsDetectors = []
        self.startTime = .distantPast
    }

    /// Creates a pipeline with the given pattern detectors and start time (for testing).
    /// No metrics detectors are added.
    public init(detectors: [PatternDetector], startTime: Date) {
        self.detectors = detectors
        self.metricsDetectors = []
        self.startTime = startTime
    }

    /// Creates a pipeline with the given pattern and metrics detectors (for testing).
    public init(
        detectors: [PatternDetector],
        metricsDetectors: [MetricsDetector]
    ) {
        self.detectors = detectors
        self.metricsDetectors = metricsDetectors
        self.startTime = .distantPast
    }

    // MARK: - Log Processing

    /// Dispatches a log entry to all enabled, accepting detectors.
    /// Returns all alerts generated by this entry.
    /// Entries with timestamps before pipeline start are ignored.
    public func process(_ entry: LogEntry) -> [Alert] {
        guard entry.timestamp >= startTime else { return [] }
        var alerts: [Alert] = []
        for detector in detectors where detector.isEnabled {
            guard detector.accepts(entry) else { continue }
            if let alert = detector.process(entry) {
                alerts.append(alert)
            }
        }
        return alerts
    }

    /// Dispatches a batch of log entries through the pipeline.
    /// More efficient than calling `process(_:)` for each entry
    /// individually, as it requires only a single actor hop.
    /// Entries with timestamps before pipeline start are ignored.
    public func processBatch(_ entries: [LogEntry]) -> [Alert] {
        var alerts: [Alert] = []
        for entry in entries {
            guard entry.timestamp >= startTime else { continue }
            for detector in detectors where detector.isEnabled {
                guard detector.accepts(entry) else { continue }
                if let alert = detector.process(entry) {
                    alerts.append(alert)
                }
            }
        }
        return alerts
    }

    // MARK: - Metrics Processing

    /// Dispatches a metrics snapshot to all enabled metrics detectors.
    /// Returns all alerts generated by this snapshot.
    public func processMetrics(_ metrics: SystemMetrics) -> [Alert] {
        var alerts: [Alert] = []
        for detector in metricsDetectors where detector.isEnabled {
            if let alert = detector.process(metrics) {
                alerts.append(alert)
            }
        }
        return alerts
    }

    // MARK: - Tick

    /// Calls `tick()` on all enabled detectors to perform periodic maintenance.
    /// Returns any time-based alerts (e.g., leaked assertion warnings).
    public func tick() -> [Alert] {
        tick(at: Date())
    }

    /// Calls `tick(at:)` on all enabled detectors using a supplied clock value.
    /// Useful for deterministic testing of time-based detectors.
    public func tick(at now: Date) -> [Alert] {
        var alerts: [Alert] = []
        for detector in detectors where detector.isEnabled {
            let tickAlerts = detector.tick(at: now)
            alerts.append(contentsOf: tickAlerts)
        }
        for detector in metricsDetectors where detector.isEnabled {
            let tickAlerts = detector.tick(at: now)
            alerts.append(contentsOf: tickAlerts)
        }
        return alerts
    }

    // MARK: - Detector Management

    /// The total number of detectors in the pipeline (pattern + metrics).
    public var detectorCount: Int {
        detectors.count + metricsDetectors.count
    }

    /// All detector IDs in the pipeline (pattern + metrics).
    public var detectorIDs: [String] {
        detectors.map { $0.id } + metricsDetectors.map { $0.id }
    }

    /// Checks whether a detector is enabled.
    /// Returns `nil` if the detector ID is not found.
    public func isEnabled(detectorID: String) -> Bool? {
        if let d = detectors.first(where: { $0.id == detectorID }) {
            return d.isEnabled
        }
        if let d = metricsDetectors.first(where: { $0.id == detectorID }) {
            return d.isEnabled
        }
        return nil
    }

    /// Enables or disables a detector by ID. No-op if the ID is not found.
    public func setEnabled(_ enabled: Bool, forDetectorID id: String) {
        if let detector = detectors.first(where: { $0.id == id }) {
            detector.isEnabled = enabled
            return
        }
        if let detector = metricsDetectors.first(where: { $0.id == id }) {
            detector.isEnabled = enabled
            return
        }
    }
}
