import Foundation

/// Dispatches log entries to pattern detectors and collects alerts.
///
/// `DetectorPipeline` is an actor that owns all pattern detectors and coordinates
/// the flow: LogEntry → accepts() filter → process() → [Alert].
///
/// Thread-safe by design (Swift actor). The pipeline:
/// 1. Iterates all enabled detectors
/// 2. Calls `accepts()` for fast filtering (subsystem/process match)
/// 3. Calls `process()` only on detectors that accept the entry
/// 4. Collects and returns all generated alerts
///
/// Periodic `tick()` calls allow detectors to emit time-based alerts
/// (e.g., StateDetector leak detection) and clean up stale state.
public actor DetectorPipeline {

    private var detectors: [PatternDetector]

    /// Creates a pipeline with all detectors from `PatternCatalog`.
    public init() {
        self.detectors = PatternCatalog.makeAll()
    }

    /// Creates a pipeline with the given detectors (for testing).
    public init(detectors: [PatternDetector]) {
        self.detectors = detectors
    }

    // MARK: - Processing

    /// Dispatches a log entry to all enabled, accepting detectors.
    /// Returns all alerts generated by this entry.
    public func process(_ entry: LogEntry) -> [Alert] {
        var alerts: [Alert] = []
        for detector in detectors where detector.isEnabled {
            guard detector.accepts(entry) else { continue }
            if let alert = detector.process(entry) {
                alerts.append(alert)
            }
        }
        return alerts
    }

    /// Calls `tick()` on all enabled detectors to perform periodic maintenance.
    /// Returns any time-based alerts (e.g., leaked assertion warnings).
    public func tick() -> [Alert] {
        var alerts: [Alert] = []
        for detector in detectors where detector.isEnabled {
            let tickAlerts = detector.tick()
            alerts.append(contentsOf: tickAlerts)
        }
        return alerts
    }

    // MARK: - Detector Management

    /// The number of detectors in the pipeline.
    public var detectorCount: Int {
        detectors.count
    }

    /// All detector IDs in the pipeline.
    public var detectorIDs: [String] {
        detectors.map { $0.id }
    }

    /// Checks whether a detector is enabled.
    /// Returns `nil` if the detector ID is not found.
    public func isEnabled(detectorID: String) -> Bool? {
        detectors.first { $0.id == detectorID }?.isEnabled
    }

    /// Enables or disables a detector by ID. No-op if the ID is not found.
    public func setEnabled(_ enabled: Bool, forDetectorID id: String) {
        guard let detector = detectors.first(where: { $0.id == id }) else { return }
        detector.isEnabled = enabled
    }
}
